//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 03:42:41 PM TRT 
//


package com.flightproviderconsumer.client.providerb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.time.LocalDateTime;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.flightproviderbconsumer.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AvailabilitySearch_QNAME = new QName("http://service.flighproviderb.com/", "availabilitySearch");
    private final static QName _AvailabilitySearchResponse_QNAME = new QName("http://service.flighproviderb.com/", "availabilitySearchResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.flightproviderbconsumer.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvailabilitySearchProviderB }
     * 
     */
    public AvailabilitySearchProviderB createAvailabilitySearch() {
        return new AvailabilitySearchProviderB();
    }

    /**
     * Create an instance of {@link AvailabilitySearchResponseProviderB }
     * 
     */
    public AvailabilitySearchResponseProviderB createAvailabilitySearchResponse() {
        return new AvailabilitySearchResponseProviderB();
    }

    /**
     * Create an instance of {@link SearchRequestProviderB }
     * 
     */
    public SearchRequestProviderB createSearchRequest() {
        return new SearchRequestProviderB();
    }

    /**
     * Create an instance of {@link SearchResultProviderB }
     * 
     */
    public SearchResultProviderB createSearchResult() {
        return new SearchResultProviderB();
    }

    /**
     * Create an instance of {@link FlightProviderB }
     * 
     */
    public FlightProviderB createFlight() {
        return new FlightProviderB();
    }

    /**
     * Create an instance of {@link LocalDateTime }
     * 
     */
    public LocalDateTime createLocalDateTime() {
        return  LocalDateTime.now();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchProviderB }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchProviderB }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.flighproviderb.com/", name = "availabilitySearch")
    public JAXBElement<AvailabilitySearchProviderB> createAvailabilitySearch(AvailabilitySearchProviderB value) {
        return new JAXBElement<AvailabilitySearchProviderB>(_AvailabilitySearch_QNAME, AvailabilitySearchProviderB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchResponseProviderB }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchResponseProviderB }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.flighproviderb.com/", name = "availabilitySearchResponse")
    public JAXBElement<AvailabilitySearchResponseProviderB> createAvailabilitySearchResponse(AvailabilitySearchResponseProviderB value) {
        return new JAXBElement<AvailabilitySearchResponseProviderB>(_AvailabilitySearchResponse_QNAME, AvailabilitySearchResponseProviderB.class, null, value);
    }

}
