//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 03:42:41 PM TRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://service.flighproviderb.com/")
package com.flightproviderconsumer.client.providerb;
