//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.03 at 03:37:06 PM TRT 
//


package com.flightproviderconsumer.client.providera;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.time.LocalDateTime;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.consumingwebservice.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AvailabilitySearch_QNAME = new QName("http://service.flighprovidera.com/", "availabilitySearch");
    private final static QName _AvailabilitySearchResponse_QNAME = new QName("http://service.flighprovidera.com/", "availabilitySearchResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.consumingwebservice.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvailabilitySearchProviderA }
     * 
     */
    public AvailabilitySearchProviderA createAvailabilitySearch() {
        return new AvailabilitySearchProviderA();
    }

    /**
     * Create an instance of {@link AvailabilitySearchResponseProviderA }
     * 
     */
    public AvailabilitySearchResponseProviderA createAvailabilitySearchResponse() {
        return new AvailabilitySearchResponseProviderA();
    }

    /**
     * Create an instance of {@link SearchRequestProviderA }
     * 
     */
    public SearchRequestProviderA createSearchRequest() {
        return new SearchRequestProviderA();
    }

    /**
     * Create an instance of {@link SearchResultProviderA }
     * 
     */
    public SearchResultProviderA createSearchResult() {
        return new SearchResultProviderA();
    }

    /**
     * Create an instance of {@link FlightProviderA }
     * 
     */
    public FlightProviderA createFlight() {
        return new FlightProviderA();
    }

    /**
     * Create an instance of {@link LocalDateTime }
     * 
     */
    public LocalDateTime createLocalDateTime() {
        return  LocalDateTime.now();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchProviderA }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchProviderA }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.flighprovidera.com/", name = "availabilitySearch")
    public JAXBElement<AvailabilitySearchProviderA> createAvailabilitySearch(AvailabilitySearchProviderA value) {
        return new JAXBElement<AvailabilitySearchProviderA>(_AvailabilitySearch_QNAME, AvailabilitySearchProviderA.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchResponseProviderA }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AvailabilitySearchResponseProviderA }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.flighprovidera.com/", name = "availabilitySearchResponse")
    public JAXBElement<AvailabilitySearchResponseProviderA> createAvailabilitySearchResponse(AvailabilitySearchResponseProviderA value) {
        return new JAXBElement<AvailabilitySearchResponseProviderA>(_AvailabilitySearchResponse_QNAME, AvailabilitySearchResponseProviderA.class, null, value);
    }

}
